"""Add notification preferences and muted conversations

Revision ID: 2c89043a3e03
Revises: 3142328c41e2
Create Date: 2025-11-27 15:39:25.446081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c89043a3e03'
down_revision: Union[str, None] = '3142328c41e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('sound_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sound_volume', sa.Integer(), server_default='75', nullable=False),
    sa.Column('browser_notifications_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('enable_message_notifications', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('enable_mention_notifications', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('enable_reaction_notifications', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('enable_member_activity_notifications', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('dnd_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('dnd_start', sa.Time(), nullable=True),
    sa.Column('dnd_end', sa.Time(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.create_table('muted_conversations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('muted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'conversation_id', name='uq_muted_conversations_user_conversation')
    )
    op.create_index('ix_muted_conversations_conversation_id', 'muted_conversations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_muted_conversations_user_id'), 'muted_conversations', ['user_id'], unique=False)
    op.drop_index('idx_conversation_members_user_conversation', table_name='conversation_members')
    op.drop_index('idx_conversations_name_trgm', table_name='conversations', postgresql_using='gin', postgresql_where='(name IS NOT NULL)')
    op.drop_index('idx_message_status_message_user', table_name='message_status')
    op.drop_index('idx_message_status_user_unread', table_name='message_status', postgresql_where="((status)::text <> 'read'::text)")
    op.alter_column('messages', 'type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('TEXT', 'IMAGE', 'FILE', 'VOICE', 'POLL', 'CALL', 'SYSTEM', name='message_type', native_enum=False),
               existing_nullable=False)
    op.drop_index('idx_messages_content_trgm', table_name='messages', postgresql_using='gin')
    op.drop_index('idx_messages_content_tsv', table_name='messages', postgresql_using='gin')
    op.drop_index('idx_messages_conversation_created_id', table_name='messages', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_messages_conversation_id_search', table_name='messages', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_messages_reply_to_id', table_name='messages', postgresql_where='(reply_to_id IS NOT NULL)')
    op.drop_index('idx_messages_sender_id', table_name='messages')
    op.drop_column('messages', 'content_tsv')
    op.add_column('users', sa.Column('contact_number', sa.String(length=50), nullable=True))
    op.drop_index('idx_users_first_name_trgm', table_name='users', postgresql_using='gin')
    op.drop_index('idx_users_last_name_trgm', table_name='users', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_last_name_trgm', 'users', [sa.text('lower(last_name::text)')], unique=False, postgresql_using='gin')
    op.create_index('idx_users_first_name_trgm', 'users', [sa.text('lower(first_name::text)')], unique=False, postgresql_using='gin')
    op.drop_column('users', 'contact_number')
    op.add_column('messages', sa.Column('content_tsv', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.create_index('idx_messages_sender_id', 'messages', ['sender_id'], unique=False)
    op.create_index('idx_messages_reply_to_id', 'messages', ['reply_to_id'], unique=False, postgresql_where='(reply_to_id IS NOT NULL)')
    op.create_index('idx_messages_conversation_id_search', 'messages', ['conversation_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_messages_conversation_created_id', 'messages', ['conversation_id', sa.text('created_at DESC'), sa.text('id DESC')], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_messages_content_tsv', 'messages', ['content_tsv'], unique=False, postgresql_using='gin')
    op.create_index('idx_messages_content_trgm', 'messages', ['content'], unique=False, postgresql_using='gin')
    op.alter_column('messages', 'type',
               existing_type=sa.Enum('TEXT', 'IMAGE', 'FILE', 'VOICE', 'POLL', 'CALL', 'SYSTEM', name='message_type', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.create_index('idx_message_status_user_unread', 'message_status', ['user_id', 'message_id'], unique=False, postgresql_where="((status)::text <> 'read'::text)")
    op.create_index('idx_message_status_message_user', 'message_status', ['message_id', 'user_id', 'status'], unique=False)
    op.create_index('idx_conversations_name_trgm', 'conversations', [sa.text('lower(name::text)')], unique=False, postgresql_using='gin', postgresql_where='(name IS NOT NULL)')
    op.create_index('idx_conversation_members_user_conversation', 'conversation_members', ['user_id', 'conversation_id'], unique=False)
    op.drop_index(op.f('ix_muted_conversations_user_id'), table_name='muted_conversations')
    op.drop_index('ix_muted_conversations_conversation_id', table_name='muted_conversations')
    op.drop_table('muted_conversations')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
