"""Initial database schema

Revision ID: 60ae1209ded0
Revises: 
Create Date: 2025-10-10 08:29:36.516988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60ae1209ded0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('tms_user_id', sa.String(length=255), nullable=False),
    sa.Column('settings_json', sa.JSON(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_tms_user_id', 'users', ['tms_user_id'], unique=False)
    op.create_index(op.f('ix_users_tms_user_id'), 'users', ['tms_user_id'], unique=True)
    op.create_table('conversations',
    sa.Column('type', sa.Enum('DM', 'GROUP', name='conversation_type', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_created_by', 'conversations', ['created_by'], unique=False)
    op.create_index('idx_conversations_type', 'conversations', ['type'], unique=False)
    op.create_table('user_blocks',
    sa.Column('blocker_id', sa.Uuid(), nullable=False),
    sa.Column('blocked_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blocker_id', 'blocked_id')
    )
    op.create_index('idx_user_blocks_blocked', 'user_blocks', ['blocked_id'], unique=False)
    op.create_index('idx_user_blocks_blocker', 'user_blocks', ['blocker_id'], unique=False)
    op.create_table('calls',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('VOICE', 'VIDEO', name='call_type', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'MISSED', 'DECLINED', 'CANCELLED', name='call_status', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_calls_conversation', 'calls', ['conversation_id'], unique=False)
    op.create_index('idx_calls_created_at', 'calls', ['created_at'], unique=False)
    op.create_index('idx_calls_created_by', 'calls', ['created_by'], unique=False)
    op.create_index(op.f('ix_calls_conversation_id'), 'calls', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_calls_created_by'), 'calls', ['created_by'], unique=False)
    op.create_table('conversation_members',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', name='conversation_role', native_enum=False), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('last_read_at', sa.DateTime(), nullable=True),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.Column('mute_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', 'user_id')
    )
    op.create_index('idx_conversation_members_conversation', 'conversation_members', ['conversation_id'], unique=False)
    op.create_index('idx_conversation_members_user', 'conversation_members', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('TEXT', 'IMAGE', 'FILE', 'VOICE', 'POLL', 'CALL', name='message_type', native_enum=False), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('reply_to_id', sa.Uuid(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_conversation_created', 'messages', ['conversation_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_messages_reply_to', 'messages', ['reply_to_id'], unique=False)
    op.create_index('idx_messages_sender', 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_reply_to_id'), 'messages', ['reply_to_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('call_participants',
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('call_id', 'user_id')
    )
    op.create_index('idx_call_participants_call', 'call_participants', ['call_id'], unique=False)
    op.create_index('idx_call_participants_user', 'call_participants', ['user_id'], unique=False)
    op.create_table('message_reactions',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', 'emoji', name='uq_message_user_emoji')
    )
    op.create_index('idx_message_reactions_message', 'message_reactions', ['message_id'], unique=False)
    op.create_index('idx_message_reactions_user', 'message_reactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_message_reactions_message_id'), 'message_reactions', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_reactions_user_id'), 'message_reactions', ['user_id'], unique=False)
    op.create_table('message_status',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'DELIVERED', 'READ', name='message_status_type', native_enum=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'user_id')
    )
    op.create_index('idx_message_status_user', 'message_status', ['user_id', 'status'], unique=False)
    op.create_table('polls',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('multiple_choice', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index('idx_polls_message', 'polls', ['message_id'], unique=False)
    op.create_table('poll_options',
    sa.Column('poll_id', sa.Uuid(), nullable=False),
    sa.Column('option_text', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_poll_options_poll', 'poll_options', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_options_poll_id'), 'poll_options', ['poll_id'], unique=False)
    op.create_table('poll_votes',
    sa.Column('poll_id', sa.Uuid(), nullable=False),
    sa.Column('option_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['poll_options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'option_id', 'user_id', name='uq_poll_option_user')
    )
    op.create_index('idx_poll_votes_option', 'poll_votes', ['option_id'], unique=False)
    op.create_index('idx_poll_votes_poll', 'poll_votes', ['poll_id'], unique=False)
    op.create_index('idx_poll_votes_user', 'poll_votes', ['user_id'], unique=False)
    op.create_index(op.f('ix_poll_votes_option_id'), 'poll_votes', ['option_id'], unique=False)
    op.create_index(op.f('ix_poll_votes_poll_id'), 'poll_votes', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_votes_user_id'), 'poll_votes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poll_votes_user_id'), table_name='poll_votes')
    op.drop_index(op.f('ix_poll_votes_poll_id'), table_name='poll_votes')
    op.drop_index(op.f('ix_poll_votes_option_id'), table_name='poll_votes')
    op.drop_index('idx_poll_votes_user', table_name='poll_votes')
    op.drop_index('idx_poll_votes_poll', table_name='poll_votes')
    op.drop_index('idx_poll_votes_option', table_name='poll_votes')
    op.drop_table('poll_votes')
    op.drop_index(op.f('ix_poll_options_poll_id'), table_name='poll_options')
    op.drop_index('idx_poll_options_poll', table_name='poll_options')
    op.drop_table('poll_options')
    op.drop_index('idx_polls_message', table_name='polls')
    op.drop_table('polls')
    op.drop_index('idx_message_status_user', table_name='message_status')
    op.drop_table('message_status')
    op.drop_index(op.f('ix_message_reactions_user_id'), table_name='message_reactions')
    op.drop_index(op.f('ix_message_reactions_message_id'), table_name='message_reactions')
    op.drop_index('idx_message_reactions_user', table_name='message_reactions')
    op.drop_index('idx_message_reactions_message', table_name='message_reactions')
    op.drop_table('message_reactions')
    op.drop_index('idx_call_participants_user', table_name='call_participants')
    op.drop_index('idx_call_participants_call', table_name='call_participants')
    op.drop_table('call_participants')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_reply_to_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('idx_messages_sender', table_name='messages')
    op.drop_index('idx_messages_reply_to', table_name='messages')
    op.drop_index('idx_messages_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_conversation_members_user', table_name='conversation_members')
    op.drop_index('idx_conversation_members_conversation', table_name='conversation_members')
    op.drop_table('conversation_members')
    op.drop_index(op.f('ix_calls_created_by'), table_name='calls')
    op.drop_index(op.f('ix_calls_conversation_id'), table_name='calls')
    op.drop_index('idx_calls_created_by', table_name='calls')
    op.drop_index('idx_calls_created_at', table_name='calls')
    op.drop_index('idx_calls_conversation', table_name='calls')
    op.drop_table('calls')
    op.drop_index('idx_user_blocks_blocker', table_name='user_blocks')
    op.drop_index('idx_user_blocks_blocked', table_name='user_blocks')
    op.drop_table('user_blocks')
    op.drop_index('idx_conversations_type', table_name='conversations')
    op.drop_index('idx_conversations_created_by', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_tms_user_id'), table_name='users')
    op.drop_index('idx_users_tms_user_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
