"""add_tms_user_fields

Revision ID: b2ec88244e3f
Revises: ca5757ce1afe
Create Date: 2025-10-13 09:58:32.352154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ec88244e3f'
down_revision: Union[str, None] = 'ca5757ce1afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('middle_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('image', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('contact_number', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('position_title', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('division', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('section', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('custom_team', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('hierarchy_level', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('reports_to_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_leader', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_users_department'), 'users', ['department'], unique=False)
    op.create_index(op.f('ix_users_division'), 'users', ['division'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_division'), table_name='users')
    op.drop_index(op.f('ix_users_department'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'is_leader')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'reports_to_id')
    op.drop_column('users', 'hierarchy_level')
    op.drop_column('users', 'custom_team')
    op.drop_column('users', 'section')
    op.drop_column('users', 'department')
    op.drop_column('users', 'division')
    op.drop_column('users', 'position_title')
    op.drop_column('users', 'role')
    op.drop_column('users', 'image')
    op.drop_column('users', 'contact_number')
    op.drop_column('users', 'middle_name')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'username')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
