"""Fix server defaults and remove duplicate indexes

Revision ID: ca5757ce1afe
Revises: 60ae1209ded0
Create Date: 2025-10-10 09:01:20.040714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca5757ce1afe'
down_revision: Union[str, None] = '60ae1209ded0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_calls_conversation', table_name='calls')
    op.drop_index('idx_calls_created_by', table_name='calls')
    op.drop_index('idx_message_reactions_message', table_name='message_reactions')
    op.drop_index('idx_message_reactions_user', table_name='message_reactions')
    op.drop_index('idx_messages_reply_to', table_name='messages')
    op.drop_index('idx_messages_sender', table_name='messages')
    op.drop_index('idx_poll_options_poll', table_name='poll_options')
    op.drop_index('idx_poll_votes_option', table_name='poll_votes')
    op.drop_index('idx_poll_votes_poll', table_name='poll_votes')
    op.drop_index('idx_poll_votes_user', table_name='poll_votes')
    op.drop_index('idx_polls_message', table_name='polls')
    op.drop_index('idx_users_tms_user_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_tms_user_id', 'users', ['tms_user_id'], unique=False)
    op.create_index('idx_polls_message', 'polls', ['message_id'], unique=False)
    op.create_index('idx_poll_votes_user', 'poll_votes', ['user_id'], unique=False)
    op.create_index('idx_poll_votes_poll', 'poll_votes', ['poll_id'], unique=False)
    op.create_index('idx_poll_votes_option', 'poll_votes', ['option_id'], unique=False)
    op.create_index('idx_poll_options_poll', 'poll_options', ['poll_id'], unique=False)
    op.create_index('idx_messages_sender', 'messages', ['sender_id'], unique=False)
    op.create_index('idx_messages_reply_to', 'messages', ['reply_to_id'], unique=False)
    op.create_index('idx_message_reactions_user', 'message_reactions', ['user_id'], unique=False)
    op.create_index('idx_message_reactions_message', 'message_reactions', ['message_id'], unique=False)
    op.create_index('idx_calls_created_by', 'calls', ['created_by'], unique=False)
    op.create_index('idx_calls_conversation', 'calls', ['conversation_id'], unique=False)
    # ### end Alembic commands ###
